<?php

namespace Database\Seeders;

use App\Models\Recipes\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'agrest',
            'ajerkoniak',
            'ananas',
            'ananas z puszki',
            'anchois filet',
            'antrykot wołowy',
            'arbuz',
            'awokado',
            'babeczka śmietankowa',
            'babka piaskowa',
            'babka polska',
            'bagietka francuska',
            'bajaderka',
            'bakłażan',
            'bakłażan smażony na oleju',
            'bambus konserwowy',
            'banan',
            'baranina bez kości',
            'baranina łopatka',
            'baranina udziec',
            'barszcz z uszkami',
            'baton Bounty',
            'baton Duplo',
            'baton Kitekat',
            'baton Mars',
            'baton Milky Way',
            'baton Snickers',
            'bażant',
            'beza',
            'bigos domowy',
            'bigos popularny',
            'bitki wieprzowe',
            'bitki wołowe',
            'bliny ziemniaczane',
            'boczek faszerowany',
            'boczek wędzony solony',
            'boczek wieprzowy',
            'boćwina',
            'borówki',
            'bób',
            'brokuły',
            'brukselka',
            'brukselka z wody z bułką tartą i masłem',
            'bryndza ser owczy',
            'brzoskwinia',
            'brzoskwinie suszone',
            'bułka grahamka',
            'bułka kajzerka',
            'bułka maślana',
            'bułka pszenna',
            'bułka tarta',
            'buraki ćwikłowe',
            'buraki zasmażane',
            'cappuccino z mlekiem',
            'cebula',
            'chałka',
            'chałwa',
            'chipsy ziemniaczane',
            'chipsy ziemniaczane',
            'chleb graham',
            'chleb lecytynowy',
            'chleb pita',
            'chleb pszenny',
            'chleb pumpernikiel',
            'chleb razowy na miodzie',
            'chleb razowy',
            'chleb sitkowy',
            'chleb słodowy',
            'chleb z otrębami',
            'chleb zwykły',
            'chleb ytni',
            'chrzan',
            'ciastka delicje szampańskie',
            'ciastka markizy',
            'ciastko karpatka',
            'ciastka tortowe z galaretką',
            'ciasto drożdżowe ze śliwkami',
            'ciasto kokosowe',
            'ciasto kruche ze śliwkami',
            'cielęca pieczeń duszona',
            'cielęca wątróbka',
            'cielęce klopsiki mielone',
            'cielęce nerki surowe',
            'cielęce serca',
            'cielęcina bez kości',
            'cielęcina w potrawce',
            'cielęcina nerkówka',
            'cielęcina łopatka',
            'cielęcina udziec',
            'cielęcy kotlet panierowany',
            'cielęcy mózg',
            'cielęcy ozór surowy',
            'Coca Cola light',
            'Coca Cola',
            'croissant',
            'crunchips',
            'cukier biały',
            'cukier waniliowy  paczka',
            'cukierki M&M',
            'cukierki',
            'cukinia',
            'cykoria',
            'cynamon',
            'cytryna  średnia',
            'czarne jagody',
            'czekolada  kostka',
            'czekolada do picia w proszku',
            'czekolada gorzka',
            'czekolada kremowa',
            'czekolada Milka mleczna',
            'czekolada Milka z jogurtem',
            'czekolada Milka z truskawkami',
            'czekolada Milka ze wiśniami',
            'czekolada mleczna',
            'czekoladka Ferrero Rocher',
            'czekoladka Mon Cheri',
            'czekoladowa posypka do deserów',
            'czekoladowy mus',
            'czereśnie',
            'czosnek  ząbek',
            'ćwikła',
            'daktyle suszone',
            'dorsz po grecku  porcja',
            'dorsz w sosie pomidorowym konserwa',
            'dorsz wędzony',
            'dorsz filety smażone panierowane',
            'dorsz kotlet mielony',
            'draże arachidowe Wedel',
            'drobiowa wątróbka',
            'drobiowe serca',
            'drops owocowy',
            'drożdże prasowane',
            'drożdże suszone  paczka',
            'drożdżówka z makiem',
            'drożdżówka z marmoladą',
            'dynia',
            'dzik szynka',
            'dżem śliwkowy niskosłodzony',
            'dżem truskawkowy',
            'dżem z czarnej porzeczki niskosłodzony',
            'eklerka z kremem',
            'Fanta',
            'fasola biała sucha',
            'fasola czarna sucha',
            'fasola kolorowa sucha',
            'fasola mungo',
            'fasolka cięta w zalewie konserwa',
            'fasolka po bretońsku',
            'fasolka szparagowa',
            'fasolka szparagowa z bułką tartą',
            'faworki',
            'feta ser grecki',
            'figi suszone',
            'figi świeŻe',
            'flaki surowe',
            'flaki',
            'flądra wędzona',
            'frytki ziemniaczane podsmażane mrożone',
            'galaretka owocowa w proszku',
            'galaretka z nóżek wieprzowych',
            'gęś tuszka',
            'gołąbki w sosie pomidorowym',
            'granat',
            'grejfrut',
            'groch suchy',
            'groszek w zalewie konserwa',
            'groszek z marchewką',
            'groszek zielony strąki',
            'groszek zielony z masłem',
            'gruszka',
            'gruszki suszone',
            'gruszki w syropie w puszce',
            'grzyby suszone',
            'gulasz sojowy z jarzynami',
            'gulasz wieprzowo-wołowy',
            'gulasz wołowy',
            'hamburger Bic Mac',
            'hamburger Royal',
            'hamburger rybny',
            'hamburger z serem',
            'hamburger',
            'herbata mrożona Lipton Ice Tea',
            'herbatnik',
            'herbatniki w czekoladzie',
            'homar',
            'indyk białe mięso ze skórą',
            'indyk filet',
            'indyk tuszka',
            'irysy',
            'jabłecznik',
            'jabłka suszone',
            'jabłko świeże',
            'jaja przepiórcze',
            'jaja sadzone',
            'jajecznica na słoninie',
            'jajo   ok.',
            'jajo Żółtko',
            'jarmuż',
            'jarzynowa zupa',
            'jarzynowa zupa zabielana',
            'jeżyny',
            'jogurt Danone',
            'jogurt naturalny',
            'jogurt owocowy',
            'jogurt z kawałkami owoców Danone',
            'kabaczek',
            'kaczka mięso z piersi',
            'kaczka mięso z udka',
            'kaczka tuszka',
            'kakao na mleku',
            'kakao',
            'kalafior',
            'kalafior z wody z bułką tartą',
            'kalafior',
            'kalarepa',
            'kapary stołowa',
            'kapusta biała',
            'kapusta biała zasmażana',
            'kapusta biała surówka',
            'kapusta czerwona',
            'kapusta czerwona sałatka',
            'kapusta kiszona',
            'kapusta kwaszona surówka',
            'kapusta włoska',
            'kapuśniak z kapusty kwaszonej',
            'kapuśniak ze słodkiej kapusty',
            'karczochy',
            'karmelki light',
            'karmelki tradycyjne',
            'karp walarecie',
            'karp z wody',
            'karp części jadalne',
            'kaszaryczana na sypko',
            'kaszaryczana sucha',
            'kasza jęczmienna perłowa sucha',
            'kasza jęczmienna pęczak sucha',
            'kasza manna sucha',
            'kasza perłowa na sypko',
            'kasza z pszenicy kus kus sucha',
            'kaszanka',
            'kawior prawdziwy',
            'kefir',
            'keks owocowy',
            'ketchup pomidorowy Heinz',
            'ketchup pomidorowy',
            'kiełbasa husarska',
            'kiełbasa kabanos',
            'kiełbasa krakowska',
            'kiełbasa krakowska parzona',
            'kiełbasa krakowska sucha',
            'kiełbasa metka',
            'kiełbasa myśliwska',
            'kiełbasa parówkowa',
            'kiełbasa salami',
            'kiełbasa szynkowa',
            'kiełbasa zwyczajna',
            'kiełki lucerny',
            'kiełki sojowe',
            'kiełki sojowe z puszki',
            'kiwi',
            'klopsiki cielęce mielone',
            'kluski kładzione',
            'kluski lane',
            'knedle ze śliwkami',
            'kompot jabłkowy',
            'kompot truskawkowy',
            'koncentrat barszczu czerwonego',
            'koncentrat pomidorowy',
            'konina bez kości',
            'konserwa luncheon meat',
            'konserwa turystyczna',
            'koperek',
            'kopytka z masłem',
            'kotlet z drobiu panierowany',
            'kotlet schabowy',
            'kotlety mielone wieprzowo-wołowe',
            'kraby',
            'krakers',
            'krewetki',
            'królik mięso bez kości',
            'krówki cukierki',
            'krupnik z kaszy jęczmiennej',
            'kukurydza w puszce',
            'kukurydza  kolba',
            'kukurydziane chrupki',
            'kura w galarecie',
            'kura tuszka',
            'kurczak pieczony',
            'kurczak  skrzydełko',
            'kurczak  udko',
            'kurczak białe mięso bez skóry',
            'kuropatwa',
            'kutia',
            'likier curacao',
            'lin',
            'lody bakaliowe',
            'lody Bounty',
            'lody kakaowe',
            'lody Magnum białe',
            'lody Magnum w czekoladzie',
            'lody Mars',
            'lody Milky Way',
            'lody mleczne',
            'lody mleczne  kulka',
            'lody mleczno-owocowe  kulka',
            'lody Snickers',
            'lody śmietankowe  kulka',
            'lukier ciemny',
            'lukier jasny',
            'łosoś części jadalne',
            'łosoś wędzony',
            'majonez',
            'mak',
            'makowiec',
            'makrela w sosie własnym',
            'makrela wędzona',
            'makrela',
            'maliny',
            'małże',
            'mandarynki w syropie',
            'mandarynki we własnym soku',
            'mandarynki',
            'mango w syropie',
            'mango',
            'marchew',
            'margaryna Bona',
            'margaryna Kama',
            'margaryna Kasia',
            'margaryna Medium',
            'margaryna Maryna',
            'margaryna mleczna',
            'margaryna Palma',
            'margaryna Rama',
            'margaryna Sawa',
            'margaryna Słoneczna',
            'margaryna Śniadaniowa',
            'margaryna Udana',
            'margaryna Zwykła',
            'marmolada',
            'Marsala',
            'Martini wytrawne  cl',
            'masło Finea Mix',
            'masło Masmix',
            'masło orzechowe',
            'masło roślinne MR',
            'masło roślinne Nova',
            'maślak',
            'maślanka',
            'mąka gryczana',
            'mąka pszenna krupczatka',
            'mąka pszenna poznańska',
            'mąka pszenna wrocławska',
            'mąka pszenna',
            'mąka ryżowa',
            'mąka sojowa',
            'mąka ziemniaczana',
            'melon',
            'mielonka wieprzowa konserwa',
            'migdały słodkie',
            'mintaj części jadalne',
            'miód pszczeli',
            'miód pszczeli',
            'miód uczny',
            'miśki Żelatynowe',
            'mizeria ze śmietaną',
            'mleko',
            'mleko kozie',
            'mleko',
            'mleko zagęszczone niesłodzone',
            'mleko zagęszczone słodzone',
            'mleko zsiadłe',
            'morele świeże',
            'morele w syropie w puszce',
            'morszczuk części jadalne',
            'mortadela',
            'musli z owocami suszonymi Dr. Oetker z mlekiem',
            'musli z owocami tropikalnymi Nestle',
            'musztarda',
            'naleśniki z kapustą',
            'naleśniki z serem',
            'napoleonki',
            'nektarynka',
            'Nutella',
            'ogórek',
            'ogórek kiszony',
            'ogórek konserwowy',
            'okoń części jadalne',
            'oleje roślinne',
            'oliwa z oliwek',
            'oliwki czarne marynowane',
            'oliwki zielone marynowane',
            'ocet bez dodatków',
            'ocet z dodatkami',
            'orzechy nerkowce obrane',
            'orzechy laskowe obrane',
            'orzechy pecan obrane',
            'orzechy pistacjowe obrane',
            'orzechy w czekoladzie Wedel',
            'orzechy włoskie obrane',
            'orzechy ziemne obrane',
            'ostrygi',
            'otręby pszenne',
            'paluszki słone',
            'papaja',
            'papryka konserwowa',
            'papryka',
            'parówki',
            'pączek',
            'pestki dyni',
            'pestki słonecznika',
            'pieczarki',
            'pieczeń rzymska',
            'pieczywo chrupkie z sezamem',
            'pieczywo chrupkie',
            'pierniki',
            'pierniki w czekoladzie',
            'pierogi leniwe',
            'pierogi leniwe mrożone',
            'pierogi mięsne mrożone',
            'pierogi ruskie',
            'pierogi ruskie mrożone',
            'pierogi z kapustą mrożone',
            'pierogi z kapustą i grzybami',
            'pierogi z mięsem',
            'cebula',
            'pierogi z serem',
            'pierogi z truskawkami',
            'pietruszka korzeń',
            'pietruszka natka',
            'pigwa',
            'pikling wędzony',
            'piwo guiness',
            'piwo jasne',
            'piwo pilsner',
            'piwo słodowe',
            'placek drożdżowy z kruszonką',
            'płatki kukurydziane',
            'płatki owsiane',
            'polędwica wędzona  plasterek',
            'pomarańcza',
            'pomidor',
            'pomidory w puszce',
            'popcorn',
            'pory',
            'porzeczki białe',
            'porzeczki czarne',
            'porzeczki czerwone',
            'powidła śliwkowe',
            'poziomki',
            'przepiórka mięso bez kości',
            'pstrąg części jadalne',
            'ptasie mleczko',
            'ptysie ze śmietaną',
            'pyzy z mięsem mrożone',
            'pyzy ziemniaczane mrożone',
            'rabarbar',
            'renklody',
            'risotto z mięsem i jarzynami',
            'rodzynki',
            'rogal croissant',
            'rum',
            'ryż biały',
            'ryż błyskawiczny płatki',
            'ryż ciemny',
            'ryżotowany na sypko',
            'ryż preparowany',
            'rzepa',
            'rzodkiewka',
            'salami',
            'salceson brunszwicki',
            'salceson czarny',
            'salceson ozorkowy',
            'sałata endywia',
            'sałata głowiasta',
            'sałata lodowa',
            'sałata z tuńczykiem',
            'sałata zielona z olejem słonecznikowym',
            'sałata zielona ze śmietaną',
            'sałatka śledziowa',
            'sałatka jarzynowa',
            'sałatka z białej kapusty',
            'sałatka z czerwonej kapusty',
            'sałatka z krabami',
            'sałatka ziemniaczana',
            'sandacz części jadalne',
            'Sangria',
            'sarnina',
            'schab pieczony',
            'schab wędzony',
            'seler',
            'ser biały chudy',
            'ser biały tłusty',
            'ser brie pełnotłusty',
            'ser bryndza',
            'ser camembert',
            'ser cheddar pełnotłusty',
            'ser edamski pełnotłusty',
            'ser edamski tłusty',
            'ser ementaler pełnotłusty',
            'ser ementaler tłusty',
            'ser gorgonzola pleśniowy',
            'ser gouda pełnotłusty',
            'ser gouda tłusty',
            'ser grecki feta',
            'ser mascarpone',
            'ser mozzarella pełnotłusty',
            'ser mozzarella tłusty',
            'ser myśliwski pełnotłusty',
            'ser parmezan',
            'ser rokpol pleśniowy',
            'ser roquefort pleśniowy',
            'ser salami tłusty',
            'ser sojowy tofu',
            'ser topiony',
            'ser tostowy w plasterkach',
            'ser trapisów tłusty',
            'ser tylżecki pełnotłusty',
            'ser tylżecki tłusty',
            'serdelki drobiowe',
            'sernik',
            'serek homogenizowany',
            'serek brzoskwiniowy Danone',
            'sezam',
            'skórka cytrynowa',
            'skórka pomarańczowa',
            'słonina świeża',
            'smalec',
            'soczewica gotowana',
            'soczewica sucha',
            'soja gotowana',
            'soja sucha',
            'sok pomidorowy',
            'sos sojowy',
            'sos tatarski',
            'sos winegret',
            'sól',
            'surówka z cykorii i jabłek z olejem',
            'surówka z pomidorów',
            'surówka z porów i jabłek z olejem',
            'surówka z rzodkiewki ze śmietaną',
            'surówka z selera',
            'szczaw',
            'szczupak',
            'szczypiorek',
            'szparagi',
            'szpik',
            'szpinak świeży',
            'szpinak zasmażany',
            'szprot wędzony',
            'szprot części jadalne',
            'szynka drobiowa',
            'szynka mielona konserwowa',
            'szynkowa kiełbasa',
            'śledź marynowany',
            'śledź w oleju konserwa',
            'śledź w śmietanie',
            'śledź solony',
            'ślimaki',
            'śliwki suszone',
            'śmietana 9% tłuszczu',
            'śmietana 12% tłuszczu',
            'śmietana 18% tłuszczu',
            'śmietana 22% tłuszczu',
            'śmietana 30% tłuszczu',
            'śmietana 36% tłuszczu',
            'tatar',
            'tofu',
            'torcik czekoladowy',
            'torcik waflowy',
            'tort orzechowo-śmietankowy',
            'tran',
            'trufle',
            'truskawki',
            'truskawki z bitą śmietaną',
            'tuńczyk w oleju konserwa',
            'tuńczyk w sosie własnym konserwa',
            'wafle',
            'warzywa suszone',
            'węgorz wędzony',
            'węgorz',
            'wieprzowa pieczeń',
            'wieprzowa rolada',
            'wieprzowa wątróbka surowa',
            'wieprzowe bitki',
            'wieprzowe nóżki',
            'wieprzowe serca',
            'wieprzowe żeberka duszone z cebulą',
            'wieprzowe żeberka surowe',
            'wieprzowina bez kości',
            'wieprzowina gotowana',
            'wieprzowina w sosie własnym',
            'wieprzowina boczek surowy',
            'wieprzowina golonka ze skórą',
            'wieprzowina karkówka',
            'wieprzowina łopatka chuda',
            'wieprzowina łopatka tłusta',
            'wieprzowina podgardle',
            'wieprzowina schab',
            'wieprzowina szynka chuda',
            'wieprzowina szynka tłusta',
            'wieprzowina zrazowa górna',
            'wieprzowina zrazowa przednia',
            'wieprzowina żeberka',
            'wieprzowy mózg',
            'wieprzowina schab surowy',
            'wieprzowy stek',
            'winorzane',
            'winogrona',
            'wiórki kokosowe',
            'wiśnie w czekoladzie',
            'wiśnie',
            'włoszczyzna',
            'woda mineralna',
            'woda sodowa',
            'wołowa pieczeń z polędwicy',
            'wołowa polędwica',
            'wołowa wątróbka surowa',
            'wołowe bitki',
            'wołowe nerki surowe',
            'wołowe płuca',
            'wołowina gotowana',
            'wołowina w sosie własnym',
            'wołowina antrykot',
            'wołowina goleń',
            'wołowina karkówka chuda',
            'wołowina karkówka',
            'wołowina mostek',
            'wołowina polędwica',
            'wołowina rostbef',
            'wołowina rozbratel',
            'wołowina szponder chudy',
            'wołowina szponder tłusty',
            'wołowina zrazowa dolna',
            'wołowina zrazowa górna',
            'wołowy gulasz',
            'wołowy łój',
            'wołowy mózg',
            'wołowy ozór surowy',
            'zając tuszka',
            'zarodki pszenne',
            'ziemniaczane puree w proszku',
            'ziemniaki',
            'żabie udka',
            'żeberka wieprzowe surowe',
            'żeberka',
            'żelatyna',
            'żołądki drobiowe',
            'żurawina'
        ];

        foreach ($names as $name){
            Product::insert(['name' => $name]);
        }

    }
}
