<?php

namespace Database\Seeders;

use App\Models\Recipes\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'agrest',
            'ajerkoniak',
            'ananas',
            'ananas z puszki',
            'anchois filet',
            'antrykot wołowy',
            'arbuz',
            'awokado',
            'babeczka śmietankowa',
            'babka piaskowa',
            'babka polska',
            'bagietka francuska',
            'bajaderka',
            'bakłażan',
            'bakłażan smażony na oleju',
            'bambus konserwowy',
            'banan',
            'baranina bez kości',
            'baranina łopatka',
            'baranina udziec',
            'barszcz z uszkami',
            'baton Bounty',
            'baton Duplo',
            'baton Kitekat',
            'baton Mars',
            'baton Milky Way',
            'baton Snickers',
            'bażant',
            'beza',
            'bigos domowy',
            'bigos popularny',
            'bitki wieprzowe',
            'bitki wołowe',
            'bliny ziemniaczane',
            'boczek faszerowany',
            'boczek wędzony solony',
            'boczek wieprzowy',
            'boćwina',
            'borówki',
            'bób',
            'brokuły',
            'brukselka',
            'brukselka z wody z bułką tartą i masłem',
            'bryndza ser owczy',
            'brzoskwinia',
            'brzoskwinie suszone',
            'bułka grahamka',
            'bułka kajzerka',
            'bułka maślana',
            'bułka pszenna',
            'bułka tarta',
            'buraki ćwikłowe',
            'buraki zasmażane',
            'cappuccino z mlekiem',
            'cebula',
            'chałka',
            'chałwa',
            'chipsy ziemniaczane',
            'chipsy ziemniaczane',
            'chleb graham',
            'chleb lecytynowy',
            'chleb pita',
            'chleb pszenny',
            'chleb pumpernikiel',
            'chleb razowy na miodzie',
            'chleb razowy',
            'chleb sitkowy',
            'chleb słodowy',
            'chleb z otrębami',
            'chleb zwykły',
            'chleb ytni',
            'chrzan',
            'ciastka delicje szampańskie',
            'ciastka markizy',
            'ciastko karpatka',
            'ciastka tortowe z galaretką',
            'ciasto drożdżowe ze śliwkami',
            'ciasto kokosowe',
            'ciasto kruche ze śliwkami',
            'cielęca pieczeń duszona',
            'cielęca wątróbka',
            'cielęce klopsiki mielone',
            'cielęce nerki surowe',
            'cielęce serca',
            'cielęcina bez kości',
            'cielęcina w potrawce',
            'cielęcina nerkówka',
            'cielęcina łopatka',
            'cielęcina udziec',
            'cielęcy kotlet panierowany',
            'cielęcy mózg',
            'cielęcy ozór surowy',
            'Coca Cola light',
            'Coca Cola',
            'croissant',
            'crunchips',
            'cukier biały',
            'cukier waniliowy  paczka',
            'cukierki M&M',
            'cukierki',
            'cukinia',
            'cykoria',
            'cynamon',
            'cytryna  średnia',
            'czarne jagody',
            'czekolada  kostka',
            'czekolada do picia w proszku',
            'czekolada gorzka',
            'czekolada kremowa',
            'czekolada Milka mleczna',
            'czekolada Milka z jogurtem',
            'czekolada Milka z truskawkami',
            'czekolada Milka ze wiśniami',
            'czekolada mleczna',
            'czekoladka Ferrero Rocher',
            'czekoladka Mon Cheri',
            'czekoladowa posypka do deserów',
            'czekoladowy mus',
            'czereśnie',
            'czosnek  ząbek',
            'ćwikła',
            'daktyle suszone',
            'dorsz po grecku  porcja',
            'dorsz w sosie pomidorowym konserwa',
            'dorsz wędzony',
            'dorsz filety smażone panierowane',
            'dorsz kotlet mielony',
            'draże arachidowe Wedel',
            'drobiowa wątróbka',
            'drobiowe serca',
            'drops owocowy',
            'drożdże prasowane',
            'drożdże suszone  paczka',
            'drożdżówka z makiem',
            'drożdżówka z marmoladą',
            'dynia',
            'dzik szynka',
            'dżem śliwkowy niskosłodzony',
            'dżem truskawkowy',
            'dżem z czarnej porzeczki niskosłodzony',
            'eklerka z kremem',
            'Fanta',
            'fasola biała sucha',
            'fasola czarna sucha',
            'fasola kolorowa sucha',
            'fasola mungo',
            'fasolka cięta w zalewie konserwa',
            'fasolka po bretońsku',
            'fasolka szparagowa',
            'fasolka szparagowa z bułką tartą',
            'faworki',
            'feta ser grecki',
            'figi suszone',
            'figi świeŻe',
            'flaki surowe',
            'flaki',
            'flądra wędzona',
            'frytki ziemniaczane podsmażane mrożone',
            'galaretka owocowa w proszku',
            'galaretka z nóżek wieprzowych',
            'gęś tuszka',
            'gołąbki w sosie pomidorowym',
            'granat',
            'grejfrut',
            'groch suchy',
            'groszek w zalewie konserwa',
            'groszek z marchewką',
            'groszek zielony strąki',
            'groszek zielony z masłem',
            'gruszka',
            'gruszki suszone',
            'gruszki w syropie w puszce',
            'grzyby suszone',
            'gulasz sojowy z jarzynami',
            'gulasz wieprzowo-wołowy',
            'gulasz wołowy',
            'hamburger Bic Mac',
            'hamburger Royal',
            'hamburger rybny',
            'hamburger z serem',
            'hamburger',
            'herbata mrożona Lipton Ice Tea',
            'herbatnik',
            'herbatniki w czekoladzie',
            'homar',
            'indyk białe mięso ze skórą',
            'indyk filet',
            'indyk tuszka',
            'irysy',
            'jabłecznik',
            'jabłka suszone',
            'jabłko świeże',
            'jaja przepiórcze',
            'jaja sadzone',
            'jajecznica na słoninie',
            'jajo   ok.',
            'jajo Żółtko',
            'jarmuż',
            'jarzynowa zupa',
            'jarzynowa zupa zabielana',
            'jeżyny',
            'jogurt Danone',
            'jogurt naturalny',
            'jogurt owocowy',
            'jogurt z kawałkami owoców Danone',
            'kabaczek',
            'kaczka mięso z piersi',
            'kaczka mięso z udka',
            'kaczka tuszka',
            'kakao na mleku',
            'kakao',
            'kalafior',
            'kalafior z wody z bułką tartą',
            'kalafior',
            'kalarepa',
            'kapary stołowa',
            'kapusta biała',
            'kapusta biała zasmażana',
            'kapusta biała surówka',
            'kapusta czerwona',
            'kapusta czerwona sałatka',
            'kapusta kiszona',
            'kapusta kwaszona surówka',
            'kapusta włoska',
            'kapuśniak z kapusty kwaszonej',
            'kapuśniak ze słodkiej kapusty',
            'karczochy',
            'karmelki light',
            'karmelki tradycyjne',
            'karp walarecie',
            'karp z wody',
            'karp części jadalne',
            'kaszaryczana na sypko',
            'kaszaryczana sucha',
            'kasza jęczmienna perłowa sucha',
            'kasza jęczmienna pęczak sucha',
            'kasza manna sucha',
            'kasza perłowa na sypko',
            'kasza z pszenicy kus kus sucha',
            'kaszanka',
            'kawior prawdziwy',
            'kefir',
            'keks owocowy',
            'ketchup pomidorowy Heinz',
            'ketchup pomidorowy',
            'kiełbasa husarska',
            'kiełbasa kabanos',
            'kiełbasa krakowska',
            'kiełbasa krakowska parzona',
            'kiełbasa krakowska sucha',
            'kiełbasa metka',
            'kiełbasa myśliwska',
            'kiełbasa parówkowa',
            'kiełbasa salami',
            'kiełbasa szynkowa',
            'kiełbasa zwyczajna',
            'kiełki lucerny',
            'kiełki sojowe',
            'kiełki sojowe z puszki',
            'kiwi',
            'klopsiki cielęce mielone',
            'kluski kładzione',
            'kluski lane',
            'knedle ze śliwkami',
            'kompot jabłkowy',
            'kompot truskawkowy',
            'koncentrat barszczu czerwonego',
            'koncentrat pomidorowy',
            'konina bez kości',
            'konserwa luncheon meat',
            'konserwa turystyczna',
            'koperek',
            'kopytka z masłem',
            'kotlet z drobiu panierowany',
            'kotlet schabowy',
            'kotlety mielone wieprzowo-wołowe',
            'kraby',
            'krakers',
            'krewetki',
            'królik mięso bez kości',
            'krówki cukierki',
            'krupnik z kaszy jęczmiennej',
            'kukurydza w puszce',
            'kukurydza  kolba',
            'kukurydziane chrupki',
            'kura w galarecie',
            'kura tuszka',
            'kurczak pieczony',
            'kurczak  skrzydełko',
            'kurczak  udko',
            'kurczak białe mięso bez skóry',
            'kuropatwa',
            'kutia',
            'likier curacao',
            'lin',
            'lody bakaliowe',
            'lody Bounty',
            'lody kakaowe',
            'lody Magnum białe',
            'lody Magnum w czekoladzie',
            'lody Mars',
            'lody Milky Way',
            'lody mleczne',
            'lody mleczne  kulka',
            'lody mleczno-owocowe  kulka',
            'lody Snickers',
            'lody śmietankowe  kulka',
            'lukier ciemny',
            'lukier jasny',
            'łosoś części jadalne',
            'łosoś wędzony',
            'majonez',
            'mak',
            'makowiec',
            'makrela w sosie własnym',
            'makrela wędzona',
            'makrela',
            'maliny',
            'małże',
            'mandarynki w syropie',
            'mandarynki we własnym soku',
            'mandarynki',
            'mango w syropie',
            'mango',
            'marchew',
            'margaryna Bona',
            'margaryna Kama',
            'margaryna Kasia',
            'margaryna Medium',
            'margaryna Maryna',
            'margaryna mleczna',
            'margaryna Palma',
            'margaryna Rama',
            'margaryna Sawa',
            'margaryna Słoneczna',
            'margaryna Śniadaniowa',
            'margaryna Udana',
            'margaryna Zwykła',
            'marmolada',
            'Marsala',
            'Martini wytrawne  cl',
            'masło Finea Mix',
            'masło Masmix',
            'masło orzechowe',
            'masło roślinne MR',
            'masło roślinne Nova',
            'maślak',
            'maślanka',
            'mąka gryczana',
            'mąka pszenna krupczatka',
            'mąka pszenna poznańska',
            'mąka pszenna wrocławska',
            'mąka pszenna',
            'mąka ryżowa',
            'mąka sojowa',
            'mąka ziemniaczana',
            'melon',
            'mielonka wieprzowa konserwa',
            'migdały słodkie',
            'mintaj części jadalne',
            'miód pszczeli',
            'miód pszczeli',
            'miód uczny',
            'miśki Żelatynowe',
            'mizeria ze śmietaną',
            'mleko',
            'mleko kozie',
            'mleko',
            'mleko zagęszczone niesłodzone',
            'mleko zagęszczone słodzone',
            'mleko zsiadłe',
            'morele świeże',
            'morele w syropie w puszce',
            'morszczuk części jadalne',
            'mortadela',
            'musli z owocami suszonymi Dr. Oetker z mlekiem',
            'musli z owocami tropikalnymi Nestle',
            'musztarda',
            'naleśniki z kapustą',
            'naleśniki z serem',
            'napoleonki',
            'nektarynka',
            'Nutella',
            'ogórek',
            'ogórek kiszony',
            'ogórek konserwowy',
            'okoń części jadalne',
            'oleje roślinne',
            'oliwa z oliwek',
            'oliwki czarne marynowane',
            'oliwki zielone marynowane',
            'ocet bez dodatków',
            'ocet z dodatkami',
            'orzechy nerkowce obrane',
            'orzechy laskowe obrane',
            'orzechy pecan obrane',
            'orzechy pistacjowe obrane',
            'orzechy w czekoladzie Wedel',
            'orzechy włoskie obrane',
            'orzechy ziemne obrane',
            'ostrygi',
            'otręby pszenne',
            'paluszki słone',
            'papaja',
            'papryka konserwowa',
            'papryka',
            'parówki',
            'pączek',
            'pestki dyni',
            'pestki słonecznika',
            'pieczarki',
            'pieczeń rzymska',
            'pieczywo chrupkie z sezamem',
            'pieczywo chrupkie',
            'pierniki',
            'pierniki w czekoladzie',
            'pierogi leniwe',
            'pierogi leniwe mrożone',
            'pierogi mięsne mrożone',
            'pierogi ruskie',
            'pierogi ruskie mrożone',
            'pierogi z kapustą mrożone',
            'pierogi z kapustą i grzybami',
            'pierogi z mięsem',
            'cebula',
            'pierogi z serem',
            'pierogi z truskawkami',
            'pietruszka korzeń',
            'pietruszka natka',
            'pigwa',
            'pikling wędzony',
            'piwo guiness',
            'piwo jasne',
            'piwo pilsner',
            'piwo słodowe',
            'placek drożdżowy z kruszonką',
            'płatki kukurydziane',
            'płatki owsiane',
            'polędwica wędzona  plasterek',
            'pomarańcza',
            'pomidor',
            'pomidory w puszce',
            'popcorn',
            'pory',
            'porzeczki białe',
            'porzeczki czarne',
            'porzeczki czerwone',
            'powidła śliwkowe',
            'poziomki',
            'przepiórka mięso bez kości',
            'pstrąg części jadalne',
            'ptasie mleczko',
            'ptysie ze śmietaną',
            'pyzy z mięsem mrożone',
            'pyzy ziemniaczane mrożone',
            'rabarbar',
            'renklody',
            'risotto z mięsem i jarzynami',
            'rodzynki',
            'rogal croissant',
            'rum',
            'ryż biały',
            'ryż błyskawiczny płatki',
            'ryż ciemny',
            'ryżotowany na sypko',
            'ryż preparowany',
            'rzepa',
            'rzodkiewka',
            'salami',
            'salceson brunszwicki',
            'salceson czarny',
            'salceson ozorkowy',
            'sałata endywia',
            'sałata głowiasta',
            'sałata lodowa',
            'sałata z tuńczykiem',
            'sałata zielona z olejem słonecznikowym',
            'sałata zielona ze śmietaną',
            'sałatka śledziowa',
            'sałatka jarzynowa',
            'sałatka z białej kapusty',
            'sałatka z czerwonej kapusty',
            'sałatka z krabami',
            'sałatka ziemniaczana',
            'sandacz części jadalne',
            'Sangria',
            'sarnina',
            'schab pieczony',
            'schab wędzony',
            'seler',
            'ser biały chudy',
            'ser biały tłusty',
            'ser brie pełnotłusty',
            'ser bryndza',
            'ser camembert',
            'ser cheddar pełnotłusty',
            'ser edamski pełnotłusty',
            'ser edamski tłusty',
            'ser ementaler pełnotłusty',
            'ser ementaler tłusty',
            'ser gorgonzola pleśniowy',
            'ser gouda pełnotłusty',
            'ser gouda tłusty',
            'ser grecki feta',
            'ser mascarpone',
            'ser mozzarella pełnotłusty',
            'ser mozzarella tłusty',
            'ser myśliwski pełnotłusty',
            'ser parmezan',
            'ser rokpol pleśniowy',
            'ser roquefort pleśniowy',
            'ser salami tłusty',
            'ser sojowy tofu',
            'ser topiony',
            'ser tostowy w plasterkach',
            'ser trapisów tłusty',
            'ser tylżecki pełnotłusty',
            'ser tylżecki tłusty',
            'serdelki drobiowe',
            'sernik',
            'serek homogenizowany',
            'serek brzoskwiniowy Danone',
            'sezam',
            'skórka cytrynowa',
            'skórka pomarańczowa',
            'słonina świeża',
            'smalec',
            'soczewica gotowana',
            'soczewica sucha',
            'soja gotowana',
            'soja sucha',
            'sok pomidorowy',
            'sos sojowy',
            'sos tatarski',
            'sos winegret',
            'sól',
            'surówka z cykorii i jabłek z olejem',
            'surówka z pomidorów',
            'surówka z porów i jabłek z olejem',
            'surówka z rzodkiewki ze śmietaną',
            'surówka z selera',
            'szczaw',
            'szczupak',
            'szczypiorek',
            'szparagi',
            'szpik',
            'szpinak świeży',
            'szpinak zasmażany',
            'szprot wędzony',
            'szprot części jadalne',
            'szynka drobiowa',
            'szynka mielona konserwowa',
            'szynkowa kiełbasa',
            'śledź marynowany',
            'śledź w oleju konserwa',
            'śledź w śmietanie',
            'śledź solony',
            'ślimaki',
            'śliwki suszone',
            'śmietana 9% tłuszczu',
            'śmietana 12% tłuszczu',
            'śmietana 18% tłuszczu',
            'śmietana 22% tłuszczu',
            'śmietana 30% tłuszczu',
            'śmietana 36% tłuszczu',
            'tatar',
            'tofu',
            'torcik czekoladowy',
            'torcik waflowy',
            'tort orzechowo-śmietankowy',
            'tran',
            'trufle',
            'truskawki',
            'truskawki z bitą śmietaną',
            'tuńczyk w oleju konserwa',
            'tuńczyk w sosie własnym konserwa',
            'wafle',
            'warzywa suszone',
            'węgorz wędzony',
            'węgorz',
            'wieprzowa pieczeń',
            'wieprzowa rolada',
            'wieprzowa wątróbka surowa',
            'wieprzowe bitki',
            'wieprzowe nóżki',
            'wieprzowe serca',
            'wieprzowe żeberka duszone z cebulą',
            'wieprzowe żeberka surowe',
            'wieprzowina bez kości',
            'wieprzowina gotowana',
            'wieprzowina w sosie własnym',
            'wieprzowina boczek surowy',
            'wieprzowina golonka ze skórą',
            'wieprzowina karkówka',
            'wieprzowina łopatka chuda',
            'wieprzowina łopatka tłusta',
            'wieprzowina podgardle',
            'wieprzowina schab',
            'wieprzowina szynka chuda',
            'wieprzowina szynka tłusta',
            'wieprzowina zrazowa górna',
            'wieprzowina zrazowa przednia',
            'wieprzowina żeberka',
            'wieprzowy mózg',
            'wieprzowina schab surowy',
            'wieprzowy stek',
            'winorzane',
            'winogrona',
            'wiórki kokosowe',
            'wiśnie w czekoladzie',
            'wiśnie',
            'włoszczyzna',
            'woda mineralna',
            'woda sodowa',
            'wołowa pieczeń z polędwicy',
            'wołowa polędwica',
            'wołowa wątróbka surowa',
            'wołowe bitki',
            'wołowe nerki surowe',
            'wołowe płuca',
            'wołowina gotowana',
            'wołowina w sosie własnym',
            'wołowina antrykot',
            'wołowina goleń',
            'wołowina karkówka chuda',
            'wołowina karkówka',
            'wołowina mostek',
            'wołowina polędwica',
            'wołowina rostbef',
            'wołowina rozbratel',
            'wołowina szponder chudy',
            'wołowina szponder tłusty',
            'wołowina zrazowa dolna',
            'wołowina zrazowa górna',
            'wołowy gulasz',
            'wołowy łój',
            'wołowy mózg',
            'wołowy ozór surowy',
            'zając tuszka',
            'zarodki pszenne',
            'ziemniaczane puree w proszku',
            'ziemniaki',
            'żabie udka',
            'żeberka wieprzowe surowe',
            'żeberka',
            'żelatyna',
            'żołądki drobiowe',
            'żurawina'
        ];

/*        ['name' => 'Warzywa i owoce', 'index' => 1]);
        ['name' => 'Ryby i owoce morza', 'index' => 2]);
        ['name' => 'Mięsa', 'index' => 3]);
        ['name' => 'Nabiał', 'index' => 4]);
        ['name' => 'Produkty zbożowe', 'index' => 5]);
        ['name' => 'Przyprawy i dodatki', 'index' => 6]);
        ['name' => 'Słodycze i przekąski', 'index' => 7]);
        ['name' => 'Napoje', 'index' => 8])
        ['name' => 'Higiena osobista', 'index' => 9]);
        ['name' => 'Dom', 'index' => 10]);
        ;*/

        $zboze = [
            'Amarantus',
            'Amarantus ekspandowany',
            'Amarantus organiczny',
            'Amarantus preparowany',
            'Bagietka',
            'Bagietka mała',
            'Bagietka orkiszowa',
            'Bagietka pełnoziarnista',
            'Bagietka pszenna',
            'Bagietka z masłem czosnkowym',
            'Bajgiel',
            'Błonnik',
            'Bułka ciabatta',
            'Bułka pizzerka',
            'Bułka tarta',
            'Bułki bezglutenowe',
            'Bułki do hamburgera',
            'Bułki do hot dogów',
            'Bułki do pieczenia',
            'Bułki fińskie',
            'Bułki fitness',
            'Bułki grahamki',
            'Bułki kajzerki',
            'Bułki maślane',
            'Bułki mleczne',
            'Bułki mleczne z czekoladą',
            'Bułki orkiszowe',
            'Bułki pełnoziarniste',
            'Bułki razowe',
            'Bułki wiejskie',
            'Bułki wrocławskie',
            'Bułki z musli',
            'Bułki z otrębami',
            'Bułki z serem',
            'Chałka',
            'Chia',
            'Chleb',
            'Chleb bezglutenowy',
            'Chleb biały z ziarnami',
            'Chleb chrupki',
            'Chleb ciemny',
            'Chleb czarny',
            'Chleb drwalski',
            'Chleb firmowy',
            'Chleb Fitness',
            'Chleb graham',
            'Chleb gryczany',
            'Chleb kukurydziany',
            'Chleb litewski',
            'Chleb lniany',
            'Chleb okrągły',
            'Chleb orkiszowy',
            'Chleb pełnoziarnisty',
            'Chleb pszenno żytni',
            'Chleb pszenny',
            'Chleb razowy',
            'Chleb słonecznikowy',
            'Chleb tostowy',
            'Chleb tostowy pełnoziarnisty',
            'Chleb tostowy pszenny',
            'Chleb wiejski',
            'Chleb wielozbożowy',
            'Chleb żytni',
            'Chlebek chrupki',
            'Chlebek Pita',
            'Ciabatta',
            'Drożdżówka',
            'Focaccia',
            'Granola',
            'Groszek ptysiowy',
            'Grzanki',
            'Jagodzianka (ciastko)',
            'Jaśki - poduszeczki kokosowe',
            'Kasza bulgur',
            'Kasza gryczana',
            'Kasza gryczana niepalona',
            'Kasza gryczana prażona',
            'Kasza jaglana',
            'Kasza jęczmienna',
            'Kasza kukurydziana',
            'Kasza kuskus',
            'Kasza manna',
            'Kasza orkiszowa',
            'Kasza owsiana',
            'Kasza pęczak',
            'Kasza perłowa',
            'Kasza quinoa',
            'Kaszka manna',
            'Kaszka ryżowa',
            'Kleik',
            'Kołacz',
            'Komosa ryżowa',
            'Maca',
            'Mąka gryczana',
            'Mąka jaglana',
            'Mąka jęczmienna',
            'Mąka kokosowa',
            'Mąka konopna',
            'Mąka kukurydziana',
            'Mąka orkiszowa',
            'Mąka owsiana',
            'Mąka pszenna',
            'Mąka pszenna graham typ 1850',
            'Mąka pszenna razowa typ 2000',
            'Mąka pszenna tortowa typ 450',
            'Mąka pszenna typ 650',
            'Mąka pszenna typ 750',
            'Mąka razowa',
            'Mąka ryżowa',
            'Mąka ryżowa brązowa',
            'Mąka sojowa',
            'Mąka ziemniaczana',
            'Mąka żytnia pełnoziarnista',
            'Mąka żytnia razowa',
            'Makaron',
            'Makaron bezglutenowy',
            'Makaron bezjajeczny',
            'Makaron chiński',
            'Makaron conchiglioni',
            'Makaron domowy',
            'Makaron durum',
            'Makaron fusili',
            'Makaron gniazda',
            'Makaron graham',
            'Makaron gryczany',
            'Makaron japoński',
            'Makaron kokardki',
            'Makaron kolanka',
            'Makaron krajanka',
            'Makaron lasagne',
            'Makaron muszelki',
            'Makaron nitki',
            'Makaron orkiszowy',
            'Makaron penne',
            'Makaron somen',
            'Makaron spaghetti',
            'Makaron świderki',
            'Makaron tagliatelle',
            'Makaron udon',
            'Makaron wstążki',
            'Makaron ze szpinakiem',
            'Musli',
            'Musli crunchy',
            'Musli z orzechami',
            'Nasiona amarantusa',
            'Nasiona czarnuszki',
            'Nasiona goji',
            'Nasiona konopii łuskane',
            'Nasiona siemienia lnianego',
            'Orkisz',
            'Otręby granulowane',
            'Otręby gryczane',
            'Otręby orkiszowe',
            'Otręby owsiane',
            'Otręby pszenne',
            'Otręby żytnie',
            'Owsianka',
            'Pałeczki jaglane',
            'Papier ryżowy',
            'Pieczywo chrupkie',
            'Pieczywo chrupkie 7 ziaren',
            'Pieczywo chrupkie graham',
            'Pieczywo chrupkie kukurydziane',
            'Pieczywo chrupkie maca',
            'Pieczywo chrupkie pszenne',
            'Pieczywo chrupkie razowe',
            'Pieczywo chrupkie z sezamem',
            'Pieczywo chrupkie żytnie',
            'Pieczywo Naan',
            'Pita',
            'Płatki gryczane',
            'Płatki jaglane',
            'Płatki jęczmienne',
            'Płatki kukurydziane',
            'Płatki lniane',
            'Płatki migdałowe',
            'Płatki owsiane błyskawiczne',
            'Płatki owsiane górskie',
            'Płatki pszenne',
            'Płatki pszenne z rodzynkami i jabłkami - Vitte',
            'Płatki ryżowe',
            'Płatki z mlekiem',
            'Płatki zbożowe',
            'Płatki żytnie',
            'Płatki żytnie błyskawiczne',
            'Proso',
            'Pszenica z miodem',
            'Pumpernikiel',
            'Rogal Croissant',
            'Rogale',
            'Ryż basmati',
            'Ryż biały',
            'Ryż brązowy',
            'Ryż do sushi',
            'Ryż dziki',
            'Ryż dziki & parboiled',
            'Ryż jaśminowy',
            'Ryż paraboiled',
            'Ryż risotto',
            'Skrobia kukurydziana',
            'Skrobia ziemniaczana',
            'Spód do pizzy',
            'Sucharki',
            'Sucharki mini',
            'Tapioka',
            'Tortilla',
            'Tost pieczywo',
            'Wafle ryżowe',
            'Wafle ryżowe naturalne',
            'Wafle ryżowe wieloziarniste',
            'Wafle ryżowe z kukurydzą',
            'Wafle ryżowe z nasionami chia',
            'Wafle ryżowe z pestkami dyni',
            'Wafle ryżowe z pestkami dyni i algami morskimi',
            'Wafle ryżowe z sezamem',
            'Wafle ryżowe z solą morską',
            'Wafle ryżowe z wiesiołkiem i siemieniem lnianym',
            'Wafle ryżowe z żytem',
            'Wafle ryżowe ze słonecznikiem',
            'Zarodki pszenne',

        ];
        $mieso = [
            'Baleron',
            'Baranina',
            'Bażant',
            'Bekon',
            'Boczek',
            'Burger wołowy (surowe mięso)',
            'Cielęcina',
            'Ćwiartka kurczaka wędzona',
            'Ćwiartka z kurczaka',
            'Dziczyzna',
            'Filet z gęsi',
            'Filet z indyka',
            'Filet z kurczaka',
            'Flaki',
            'Frankfurterki',
            'Gęś',
            'Golonka',
            'Indyk',
            'Jagnięcina',
            'Kabanosy',
            'Kaczka',
            'Karczek',
            'Karkówka',
            'Kaszanka',
            'Kiełbasa',
            'Kiełbasa biała parzona',
            'Kiełbasa biała surowa',
            'Kiełbasa chorizo',
            'Kiełbasa drobiowa',
            'Kiełbasa grillowa',
            'Kiełbasa jałowcowa',
            'Kiełbasa krakowska',
            'Kiełbasa parówkowa',
            'Kiełbasa podwawelska',
            'Kiełbasa polska',
            'Kiełbasa śląska',
            'Kiełbasa swojska',
            'Kiełbasa toruńska',
            'Kiełbasa wiejska',
            'Kiełbasa z dzika',
            'Kiełbasa zwyczajna',
            'Kiełbasa żywiecka',
            'Kindziuk',
            'Konserwa turystyczna',
            'Kości wędzone',
            'Królik',
            'Kura',
            'Ligawa wołowa',
            'Łopatka',
            'Metka cebulowa',
            'Metka łososiowa',
            'Mielonka',
            'Mięso gulaszowe z indyka',
            'Mięso mielone',
            'Mięso mielone wołowe',
            'Mięso mielone z indyka',
            'Mięso mielone z łopatki wieprzowej',
            'Mięso mielone z szynki wieprzowej',
            'Ogonówka',
            'Ozory',
            'Parówki',
            'Parówki drobiowe',
            'Parówki wieprzowe',
            'Parówki z serem',
            'Pasztet',
            'Pasztet drobiowy',
            'Pasztet Dziadunia',
            'Pasztet z dzika',
            'Pasztet z gęsi',
            'Pasztet z królika',
            'Pasztet z żurawiną',
            'Pasztet ze śliwką',
            'Pasztetowa',
            'Pieczeń rzymska',
            'Pieczeń wieprzowa',
            'Pieczeń wołowa',
            'Pieczeń z kurczaka',
            'Polędwica',
            'Polędwica łososiowa',
            'Polędwica sopocka',
            'Polędwiczki',
            'Rolada',
            'Salami',
            'Salceson',
            'Salceson czarny',
            'Salceson włoski',
            'Sarnina',
            'Schab',
            'Serca drobiowe',
            'Serca wieprzowe',
            'Serdelki drobiowe',
            'Serdelki wieprzowe',
            'Serdelki z szynki',
            'Skrzydełka',
            'Słonina',
            'Smalec',
            'Stek',
            'Szynka',
            'Wątroba cielęca',
            'Wątroba wieprzowa',
            'Wątroba wołowa',
            'Wątrobianka wiejska',
            'Wędlina',
            'Wieprzowina',
            'Wołowina',
            'Żeberka',
            'Żeberka wędzone',
            'Żołądki drobiowe',

        ];
        $ryby = [
            'Amur',
            'Anchois',
            'Brzuszki z łososia wędzone',
            'Dorada',
            'Dorsz',
            'Dorsz filet',
            'Dorsz wędzony',
            'Filety z makreli w sosie pomidorowym',
            'Filety ze śledzia w sosie pomidorowym',
            'Flądra',
            'Halibut',
            'Homar',
            'Jesiotr',
            'Kalmary',
            'Karaś',
            'Karp',
            'Kawior',
            'Koreczki śledziowe',
            'Krab',
            'Krewetki',
            'Langusta',
            'Leszcz',
            'Limanda żółtopłetwa',
            'Łosoś',
            'Łosoś filet',
            'Łosoś wędzony sałatkowy',
            'Łosoś wędzony w plastrach',
            'Makrela',
            'Makrela w oleju',
            'Makrela w sosie pomidorowym',
            'Makrela wędzona',
            'Małże',
            'Marlin',
            'Miecznik',
            'Mintaj',
            'Miruna',
            'Morszczuk',
            'Okoń',
            'Ośmiornica',
            'Ostrygi',
            'Owoce morza',
            'Paluszki krabowe',
            'Paluszki rybne',
            'Paluszki Surimi',
            'Panga',
            'Pasta rybna',
            'Pikling',
            'Płoć',
            'Przegrzebki',
            'Pstrąg',
            'Rak',
            'Rolmopsy',
            'Ryba',
            'Ryba maślana',
            'Ryba panierowana',
            'Ryba z puszki',
            'Sandacz',
            'Sardynki w oleju',
            'Sardynki w sosie pomidorowym',
            'Śledź',
            'Śledź w occie',
            'Śledź w oleju',
            'Śledź w sosie pomidorowym',
            'Śledź w sosie śmietanowym',
            'Sola',
            'Sum',
            'Surimi',
            'Sushi',
            'Szczupak',
            'Szproty',
            'Szproty w oleju',
            'Szproty w sosie pomidorowym',
            'Tilapia',
            'Tołpyga',
            'Trewal wędzony',
            'Tuńczyk',
            'Tuńczyk rozdrobniony',
            'Tuńczyk w kawałkach',
            'Tuńczyk w oleju',
            'Tuńczyk w oliwie',
            'Tuńczyk w sosie własnym',
            'Tuńczyk w wodzie',
            'Turbot',
            'Węgorz świeży',
            'Węgorz wędzony',
            'Żabnica',

        ];
        $nabial = [
            'Bita śmietana spray',
            'Danonki',
            'Deser jogurtowy',
            'Deser mleczno-ryżowy',
            'Deser ryżowy',
            'Deser twarogowy',
            'Feta',
            'Jaja',
            'Jaja indycze',
            'Jaja kacze',
            'Jaja kurze',
            'Jogurt',
            'Jogurt 7 zbóż',
            'Jogurt Actimel',
            'Jogurt Alpro',
            'Jogurt bananowy',
            'Jogurt bez cukru',
            'Jogurt bez laktozy',
            'Jogurt biszkoptowy',
            'Jogurt brzoskwinia marakuja',
            'Jogurt brzoskwiniowy',
            'Jogurt czekoladowy',
            'Jogurt do picia',
            'Jogurt do picia jagodowy',
            'Jogurt do picia owoce leśne',
            'Jogurt grecki',
            'Jogurt islandzki',
            'Jogurt jagodowy',
            'Jogurt kawowy',
            'Jogurt kiwi',
            'Jogurt kokosowy',
            'Jogurt kozi',
            'Jogurt malinowy',
            'Jogurt morelowy',
            'Jogurt musli',
            'Jogurt naturalny',
            'Jogurt naturalny owczy',
            'Jogurt proteinowy',
            'Jogurt Skyr',
            'Jogurt sojowy',
            'Jogurt truskawkowy',
            'Jogurt typu greckiego',
            'Jogurt waniliowy',
            'Jogurt wieloowocowy',
            'Jogurt wiśniowy',
            'Jogurt z miodem',
            'Jogurt z musli',
            'Kefir',
            'Kefir 0%',
            'Kefir brzoskwiniowy',
            'Kefir naturalny',
            'Kefir owocowy',
            'Kefir truskawkowy',
            'Kefir waniliowy',
            'Margaryna',
            'Maślanka',
            'Maślanka brzoskwiniowa',
            'Maślanka jagodowa',
            'Maślanka stracciatella',
            'Maślanka truskawkowa',
            'Masło',
            'Masło bez laktozy',
            'Masło czosnkowe',
            'Masło osełkowe',
            'Mleczko do kawy',
            'Mleko 0%',
            'Mleko 0,5%',
            'Mleko 1,5 %',
            'Mleko 2%',
            'Mleko 3,2 %',
            'Mleko bez laktozy',
            'Mleko czekoladowe',
            'Mleko kokosowe',
            'Mleko kozie',
            'Mleko odtłuszczone w kartonie',
            'Mleko odtłuszczone w proszku',
            'Mleko orzechowe',
            'Mleko owcze',
            'Mleko owsiane',
            'Mleko skondensowane',
            'Mleko skondensowane niesłodzone',
            'Mleko smakowe',
            'Mleko sojowe',
            'Mleko w proszku',
            'Mleko waniliowe',
            'Mleko z nerkowców',
            'Mleko zagęszczone',
            'Mleko zsiadłe',
            'Mozzarella',
            'Mozzarella mini',
            'Napój migdałowy',
            'Napój mleczny',
            'Napój owsiany',
            'Napój sojowy',
            'Oscypek',
            'Oscypek wędzony',
            'Pudding',
            'Ryż na mleku',
            'Ser Babuni',
            'Ser biały',
            'Ser biały bez laktozy',
            'Ser biały chudy',
            'Ser biały kozi',
            'Ser biały owczy',
            'Ser biały półtłusty',
            'Ser biały tłusty',
            'Ser biały twaróg',
            'Ser biały wędzony',
            'Ser brie',
            'Ser Bryndza',
            'Ser Camembert',
            'Ser Carski',
            'Ser Cheddar',
            'Ser Edam',
            'Ser Edamer',
            'Ser Edamski',
            'Ser Feta',
            'Ser Feta mini',
            'Ser Fromage',
            'Ser Gouda',
            'Ser Halloumi',
            'Ser kozi',
            'Ser Królewski',
            'ser Maasdam',
            'Ser Maasdamer',
            'Ser Mozzarella',
            'Ser Mozzarella mini',
            'Ser Mozzarella świeża',
            'Ser Mozzarella tarty',
            'Ser Mozzarella w zalewie',
            'Ser owczy',
            'Ser Parmezan',
            'Ser Philadelphia',
            'Ser pleśniowy',
            'Ser pleśniowy błękitny',
            'Ser pleśniowy Gorgonzola',
            'Ser pleśniowy Lazur',
            'Ser pleśniowy Rokpol',
            'Ser Podlaski',
            'Ser podpuszczkowy',
            'Ser Radamer',
            'Ser Ricotta',
            'Ser Roquefort',
            'Ser Rycki',
            'Ser Salami',
            'Ser sałatkowo - kanapkowy',
            'Ser sałatkowy',
            'Ser smażony',
            'Ser śmietankowo-twarogowy',
            'Ser Szwajcarski',
            'Ser tarty',
            'Ser topiony',
            'Ser topiony Cheddar',
            'Ser topiony Edam',
            'Ser topiony Gouda',
            'Ser topiony kremowy',
            'Ser topiony z mleka koziego',
            'Ser topiony z papryką',
            'Ser topiony z pieczarkami',
            'Ser topiony z salami',
            'Ser topiony z szynką',
            'Ser topiony z ziołami',
            'Ser tostowy',
            'Ser twarogowy',
            'Ser Tylżycki',
            'Ser wędzony',
            'Ser włoski',
            'Ser żółty',
            'Ser żółty Babuni',
            'Ser żółty bezlaktozowy',
            'Ser żółty Edam Rycki',
            'Ser żółty Edamer',
            'Ser żółty Emmental',
            'Ser żółty Królewski - Sierpc',
            'Ser żółty light',
            'Ser żółty Maasdamer',
            'Ser żółty Masdam',
            'Ser żółty morski',
            'Ser żółty Podlaski',
            'Ser żółty Rolada Giżycka',
            'Ser żółty Rolada Ustrzycka',
            'Ser żółty wędzony',
            'Ser żółty wędzony Królewski',
            'Ser żółty wegański',
            'Ser żółty z dziurami',
            'Serek Danio',
            'Serek Danio brzoskwiniowy',
            'Serek Danio czekoladowy',
            'Serek Danio malinowy',
            'Serek Danio naturalny',
            'Serek Danio truskawkowy',
            'Serek Danio waniliowy',
            'Serek do chleba',
            'Serek do chleba śmietankowy',
            'Serek do chleba ze szczypiorkiem',
            'Serek Grani',
            'Serek homogenizowany',
            'Serek homogenizowany bananowy',
            'Serek homogenizowany brzoskwinia',
            'Serek homogenizowany czekoladowy',
            'Serek homogenizowany grecki',
            'Serek homogenizowany jagodowy',
            'Serek homogenizowany malinowy',
            'Serek homogenizowany pieczone jabłko',
            'Serek homogenizowany straccitella',
            'Serek homogenizowany truskawkowy',
            'Serek Mascarpone',
            'Serek naturalny',
            'Serek śmietankowy',
            'Serek topiony',
            'Serek twarogowy do smarowania',
            'Serek wiejski',
            'Serek wiejski bez laktozy',
            'Serek wiejski lekki',
            'Serek wiejski ze szczypiorkiem',
            'Serek z ziołami',
            'Serek ze szczypiorkiem',
            'Serek ziarnisty',
            'Skyr',
            'Śmietana',
            'Śmietana 12%',
            'Śmietana 18%',
            'Śmietana 30%',
            'Śmietanka do kawy',
            'Twaróg',
            'Twaróg chudy',
            'Twaróg do serników',
            'Twaróg półtłusty',
            'Twaróg sernikowy',
            'Twaróg tłusty',
            'Twarożek',

        ];
        $warzywa = [
            'Agrest',
            'Ananas',
            'Ananas kandyzowany',
            'Ananas suszony',
            'Ananas w plastrach',
            'Ananas w puszce',
            'Arbuz',
            'Aronia',
            'Awokado',
            'Bakłażan',
            'Banany',
            'Banany suszone',
            'Bataty',
            'Bazylia świeża',
            'Bób',
            'Boczniak',
            'Borowik suszony',
            'Borowik świeży',
            'Borówki',
            'Borówki amerykańskie',
            'Botwina',
            'Brązowa ciecierzyca konserwowa',
            'Brokuły',
            'Brokuły mrożone',
            'Brukiew',
            'Brukselka',
            'Brukselka mrożona',
            'Brzoskwinie',
            'Brzoskwinie w puszce',
            'Bukiet warzyw',
            'Buraczki',
            'Buraczki gotowane',
            'Buraczki marynowane',
            'Buraczki zasmażane',
            'Buraki tarte',
            'Cebula',
            'Cebula czerwona',
            'Cebula dymka ze szczypiorem',
            'Cebula szalotka',
            'Ciecierzyca',
            'Ciecierzyca konserwowa',
            'Ciecierzyca prażona solona',
            'Cieciorka',
            'Cieciorka w puszce',
            'Cukinia',
            'Cykoria',
            'Cytryna',
            'Czarna fasola',
            'Czereśnie',
            'Czerwona fasola',
            'Czerwona fasola w puszce',
            'Czosnek',
            'Czosnek marynowany',
            'Daktyle',
            'Daktyle suszone ',
            'Dymka cebula',
            'Dynia',
            'Dynia mrożona',
            'Dynia w occie',
            'Endywia',
            'Fasola',
            'Fasola adzuki',
            'Fasola biała',
            'Fasola biała Jaś',
            'Fasola biała w puszce',
            'Fasola czarna',
            'Fasola czarna w puszce',
            'Fasola czerwona',
            'Fasola czerwona w puszce',
            'Fasola mung',
            'Fasola mung kiełki',
            'Fasola pinto',
            'Fasola pinto w puszce',
            'Fasolka szparagowa',
            'Fasolka szparagowa mrożona',
            'Fasolka szparagowa żółta',
            'Fenkuł',
            'Figi',
            'Figi suszone',
            'Granat',
            'Grejpfrut',
            'Grejpfrut czerwony',
            'Groch',
            'Groszek',
            'Groszek cukrowy',
            'Groszek i marchewka mrożone',
            'Groszek mrożony',
            'Groszek w puszce',
            'Gruszki',
            'Grzyby',
            'Grzyby Kanie',
            'Grzyby Kurki',
            'Grzyby marynowane',
            'Grzyby Maślaki marynowane',
            'Grzyby Mun',
            'Grzyby Podgrzybki',
            'Grzyby Prawdziwki',
            'Grzyby Rydze',
            'Grzyby suszone',
            'Guava',
            'Jabłka prażone',
            'Jagody',
            'Jagody Goji',
            'Jarmuż',
            'Jeżyny',
            'Kabaczki',
            'Kaki',
            'Kalafior',
            'Kalafior mrożony',
            'Kalarepa',
            'Kapary',
            'Kapusta',
            'Kapusta biała',
            'Kapusta czerwona',
            'Kapusta kiszona',
            'Kapusta młoda',
            'Kapusta pekińska',
            'Kapusta włoska',
            'Karczochy',
            'Kasztany jadalne',
            'Kiełki',
            'Kiełki brokuła',
            'Kiełki czarnej rzepy',
            'Kiełki fasoli',
            'Kiełki lucerny',
            'Kiełki rzodkiewki',
            'Kiełki słonecznika',
            'Kiełki soczewicy',
            'Kiełki sojowe',
            'Kiwi',
            'Klementynki',
            'Kokos',
            'Koper włoski',
            'Koperek',
            'Kukurydza',
            'Kukurydza kolba',
            'Kukurydza w puszce',
            'Liczi',
            'Limonki',
            'Maliny',
            'Maliny mrożone',
            'Mandarynki',
            'Mango',
            'Maniok',
            'Marakuja',
            'Marchew',
            'Marchew mrożona',
            'Marchewka z groszkiem',
            'Marchewki mini',
            'Melon',
            'Melon żółty',
            'Miąższ kokosa',
            'Mieszanka warzywna',
            'Mieszanka warzywna chińska',
            'Mieszanka warzywna meksykańska',
            'Mieszanka warzywna śródziemnomorska',
            'Migdały',
            'Mirabelki',
            'Mix sałat',
            'Morele suszone',
            'Morele ',
            'Morwa',
            'Morwa biała',
            'Morwa czarna',
            'Mus jablkowy',
            'Natka pietruszki',
            'Nektarynki',
            'Ogórek',
            'Ogórek zielony',
            'Ogórki kiszone',
            'Ogórki konserwowe',
            'Oliwki czarne',
            'Oliwki zielone',
            'Orzechy arachidowe',
            'Orzechy brazylijskie',
            'Orzechy laskowe',
            'Orzechy makadamia',
            'Orzechy nerkowca',
            'Orzechy pekan',
            'Orzechy piniowe',
            'Orzechy pistacjowe',
            'Orzechy włoskie',
            'Orzechy ziemne',
            'Owoce leśne mrożone',
            'Papaja',
            'Papaja kandyzowana',
            'Papryczki chilli',
            'Papryka',
            'Papryka czerwona',
            'Papryka jalapeño',
            'Papryka zielona',
            'Papryka żółta',
            'Passata',
            'Pasternak',
            'Pędy bambusa',
            'Pieczarki',
            'Pietruszka korzeń',
            'Pomarańcze',
            'Pomelo',
            'Pomidory',
            'Pomidory cherry',
            'Pomidory koktajlowe',
            'Pomidory malinowe',
            'Pomidory śliwkowe',
            'Pomidory suszone',
            'Pomidory w puszce',
            'Pomidory zielone',
            'Pomidory żółte',
            'Por',
            'Porzeczki',
            'Poziomki',
            'Rabarbar',
            'Roszponka',
            'Rukola',
            'Rzepa',
            'Rzeżucha',
            'Rzodkiew biała',
            'Rzodkiewka',
            'Sałata',
            'Sałata lodowa',
            'Sałata masłowa',
            'Sałata mix',
            'Sałata rzymska',
            'Sałatka Cezar',
            'Sałatka Colesław',
            'Sałatka jarzynowa',
            'Seler',
            'Seler konserwowy',
            'Seler korzeń',
            'Seler naciowy',
            'Śliwki',
            'Śliwki suszone',
            'Śliwki węgierki',
            'Słonecznik',
            'Soczewica konserwa',
            'Soja',
            'Surówka',
            'Szczaw',
            'Szczypior',
            'Szparagi',
            'Szpinak',
            'Szpinak mrożony',
            'Szpinak ze śmietaną mrożony',
            'Trufle',
            'Truskawki',
            'Truskawki mrożone',
            'Warzywa mrożone',
            'Warzywa na patelnię',
            'Winogrona',
            'Winogrona ciemne',
            'Winogrona czerwone',
            'Winogrona zielone',
            'Wiśnie',
            'Wiśnie suszone',
            'Włoszczyzna',
            'Włoszczyzna mrożona',
            'Ziemniaki',
            'Ziemniaki młode',
            'Zupa jarzynowa mrożona',
            'Żurawina',
            'Żurawina suszona',

        ];
        $przyprawy = [
            'Agar-agar',
            'Ajwar',
            'Aromat spożywczy',
            'Bazylia',
            'Bazylia świeża',
            'Błonnik z siemieniem lnianym',
            'Bulion',
            'Bulion drobiowy',
            'Bulion kostka',
            'Bulion kostka drobiowa',
            'Bulion kostka wołowa',
            'Bulion warzywny',
            'Bulionetka',
            'Bułka tarta',
            'Cebula suszona',
            'Chili',
            'Chlorella',
            'Chrzan',
            'Chrzan tarty',
            'Chrzan żurawinowy',
            'Curry',
            'Ćwikła z chrzanem',
            'Cynamon',
            'Cząber',
            'Czarnuszka nasiona',
            'Czosnek granulowany',
            'Czosnek staropolski',
            'Dressing sałatkowy',
            'Drożdże',
            'Drożdże piekarskie suszone',
            'Drożdże piekarskie świeże',
            'Fix 4 sery z mozzarellą',
            'Fix a\'la stroganoff',
            'Fix do potraw chińskich',
            'Fix gulasz węgierski',
            'Fix gulasz z kurczakiem',
            'Fix kurczak pięć smaków po chińsku',
            'Fix przyprawa',
            'Fix smażony ryż po chińsku',
            'Fix spaghetti 4 sery z brokułami',
            'Fix spaghetti carbonara',
            'Fix świderki z kiełbasą w sosie grzybowym',
            'Fruktoza',
            'Frużelina',
            'Gałka muszkatołowa',
            'Goździki',
            'Groszek ptysiowy',
            'Guarana',
            'Hummus',
            'Imbir korzeń',
            'Imbir marynowany',
            'Imbir mielony',
            'Kakao',
            'Kakao extra ciemne',
            'Kakao naturalne',
            'Kardamon',
            'Karob',
            'Kazeina',
            'Ketchup',
            'Ketchup łagodny',
            'Ketchup pikantny',
            'Kmin rzymski',
            'Kminek',
            'Kolendra',
            'Kolendra świeża',
            'Koncentrat pomidorowy',
            'Konfitura',
            'Krem balsamiczny',
            'Krem jogurtowy',
            'Ksylitol',
            'Kurkuma',
            'Kwas chlebowy razowy',
            'Laska wanilii',
            'Len',
            'Liść laurowy',
            'Lubczyk',
            'Lukier czekoladowy',
            'Lukier kokosowy',
            'Lukier waniliowy',
            'Maggi',
            'Majeranek',
            'Majonez',
            'Mak',
            'Mąka chleba świętojańskiego',
            'Masa kajmakowa',
            'Masa makowa',
            'Masło migdałowe',
            'Masło orzechowe',
            'Mieszanka przypraw',
            'Mięta',
            'Mięta świeża',
            'Migdały płatki',
            'Miód',
            'Miód akacjowy',
            'Miód lipowy',
            'Miód spadziowy',
            'Miód wielokwiatowy',
            'Mleczko kokosowe',
            'Mus jabłkowy',
            'Musztarda',
            'Musztarda chrzanowa',
            'Musztarda delikatesowa',
            'Musztarda Dijon',
            'Musztarda francuska',
            'Musztarda kremska',
            'Musztarda miodowa',
            'Musztarda piekielna',
            'Musztarda rosyjska',
            'Musztarda sarepska',
            'Musztarda słodka',
            'Musztarda stołowa',
            'Nasiona siemienia lnianego',
            'Ocet balsamiczny',
            'Ocet jabłkowy',
            'Ocet ryżowy',
            'Ocet winny',
            'Olej',
            'Olej kokosowy',
            'Olej konopny',
            'Olej kukurydziany',
            'Olej lniany',
            'Olej migdałowy',
            'Olej ryżowy',
            'Olej rzepakowy',
            'Olej sezamowy',
            'Olej słonecznikowy',
            'Olej sojowy',
            'Oliwa',
            'Oliwa z czosnkiem',
            'Oliwa z oliwek',
            'Oregano',
            'Ostropest plamisty',
            'Panierka do mięsa i ryb',
            'Papirus pergamin do smażenia',
            'Papryka',
            'Papryka chili',
            'Papryka ostra',
            'Papryka słodka',
            'Papryka wędzona',
            'Pasta',
            'Pasta Ajwar',
            'Pasta bruschetta',
            'Pasta chrzanowa',
            'Pasta curry',
            'Pasta kokosowa',
            'Pasta oliwkowa',
            'Pasta pomidorowa',
            'Pasta sezamowa',
            'Pasta sojowa',
            'Pasta tapenada',
            'Pasta warzywna',
            'Pasta wasabi',
            'Pasta z tuńczykiem',
            'Pestki dyni',
            'Pestki słonecznika',
            'Pesto',
            'Pesto czerwone',
            'Pesto zielone',
            'Pieprz biały',
            'Pieprz cayenne',
            'Pieprz czarny',
            'Pieprz grubomielony',
            'Pieprz kolorowy',
            'Pieprz ziołowy',
            'Powidła śliwkowe',
            'Proszek do pieczenia',
            'Przecier pomidorowy',
            'Przyprawa do bigosu',
            'Przyprawa do dań z drobiu',
            'Przyprawa do grilla',
            'Przyprawa do gulaszu',
            'Przyprawa do kurczaka',
            'Przyprawa do mięs',
            'Przyprawa do piernika',
            'Przyprawa do ryb',
            'Przyprawa do ziemniaków',
            'Przyprawa gyros',
            'Przyprawa kebab',
            'Przyprawa korzenna',
            'Przyprawa kuchni włoskiej',
            'Przyprawa meksykańska',
            'Przyprawa Pomysł na',
            'Pyłek kwiatowy',
            'Pyłek pszczeli',
            'Rodzynki sułtańskie',
            'Rozmaryn suszony',
            'Sezam',
            'Sezam czarny',
            'Sezam łuskany',
            'Siemię lniane',
            'Skórka pomarańczowa',
            'Śnieżka błyskawiczna',
            'Soda',
            'Soda oczyszczona',
            'Sól',
            'Sól biała',
            'Sól himalajska',
            'Sól jodowana',
            'Sól morska',
            'Sos',
            'Sos balsamiczny',
            'Sos barbecue',
            'Sos BBQ',
            'Sos beszamelowy',
            'Sos bolognese',
            'Sos boloński',
            'Sos borowikowy',
            'Sos carbonara',
            'Sos cebulowy',
            'Sos chili pikantny',
            'Sos chili słodki',
            'Sos chiński',
            'Sos chrzanowy',
            'Sos cytrynowy',
            'Sos czekoladowy',
            'Sos czosnkowo-ziołowy',
            'Sos czosnkowy',
            'Sos do mięsa',
            'Sos do pieczeni jasny',
            'Sos francuski',
            'Sos grecki do sałatek',
            'Sos grzybowy',
            'Sos jogurtowy',
            'Sos koperkowy',
            'Sos kurkowy',
            'Sos majonezowy',
            'Sos meksykański',
            'Sos musztardowo - miodowy',
            'Sos myśliwski',
            'Sos orientalny',
            'Sos pieczarkowy',
            'Sos pomidorowy',
            'Sos sałatkowy',
            'Sos salsa',
            'Sos serowy',
            'Sos śmietanowy',
            'Sos sojowy',
            'Sos tatarski',
            'Sos teriyaki',
            'Sos truskawkowy',
            'Sos tzatziki',
            'Stevia',
            'Surówka meksykańska',
            'Surówka wielowarzywna',
            'Szafran',
            'Szałwia hiszpańska',
            'Tahini',
            'Tymianek',
            'Vegeta',
            'Vegeta',
            'Wiórki kokosowe',
            'Wiśnie kandyzowane',
            'Zabielacz do kawy',
            'Zakwas',
            'Zakwas chlebowy żytni',
            'Żelatyna',
            'Ziarenka smaku',
            'Ziarno kakaowca',
            'Ziele angielskie',
            'Zioła prowansalskie',

        ];
        $slodycze = [
            '7 Days crioissant',
            'Alpejskie Mleczko',
            'Andruty',
            'Babeczki',
            'Babka',
            'Babka cytrynowa',
            'Babka czekoladowa',
            'Babka drożdżowa',
            'Babka piaskowa',
            'Bake Rolls',
            'Baton Mars',
            'Baton Snickers',
            'Baton Twix',
            'Batony',
            'Belvita ciastka',
            'Bezy',
            'Biała czekolada',
            'Biszkopt spody',
            'Biszkopty',
            'Brownie',
            'Budyń',
            'Budyń czekoladowy',
            'Budyń malinowy',
            'Budyń śmietankowy',
            'Budyń waniliowy',
            'Bułki słodkie',
            'Cantuccini',
            'Chałwa',
            'Chipsy',
            'Chipsy bekonowe',
            'Chipsy Crunchips',
            'Chipsy fromage',
            'Chipsy krewetkowe',
            'Chipsy Lay\'s',
            'Chipsy o smaku kebaba',
            'Chipsy o smaku kurczaka',
            'Chipsy o smaku sera i cebulki',
            'Chipsy paprykowe',
            'Chipsy Pringles',
            'Chipsy serowe',
            'Chipsy solone',
            'Chrupki',
            'Ciastka',
            'Ciastka czekoladowe',
            'Ciastka francuskie',
            'Ciastka herbatniki',
            'Ciastka Hit',
            'Ciastka Jeżyki',
            'Ciastka Kokosanki',
            'Ciastka korzenne',
            'Ciastka kruche',
            'Ciastka maślane',
            'Ciastka musli',
            'Ciastka Oreo',
            'Ciastka owsiane',
            'Ciastka wielozbożowe',
            'Ciastka zbożowe',
            'ciastko z dynią',
            'Ciasto',
            'Ciasto WZ',
            'Crioissant',
            'Cukier biały',
            'Cukier brązowy',
            'Cukier cynamonowy',
            'Cukier kokosowy',
            'Cukier puder',
            'Cukier trzcinowy',
            'Cukier w kostkach',
            'Cukier waniliowy',
            'Cukierki',
            'Cukierki Cocofini',
            'Cukierki Dumle',
            'Cukierki eukaliptusowe',
            'Cukierki Halls',
            'Cukierki Irysy',
            'Cukierki karmelowe',
            'Cukierki Kinder Schoko-Bons',
            'Cukierki Krówki',
            'Cukierki Kukułki',
            'Cukierki Michałki',
            'Cukierki owocowe',
            'cukierki raczki',
            'Cukierki z alkoholem',
            'Cukierki ziołowe',
            'Cukierki Zozole',
            'Czekolada',
            'Czekolada caramel',
            'Czekolada chili',
            'Czekolada czarna',
            'Czekolada deserowa',
            'Czekolada do picia',
            'Czekolada gorzka',
            'Czekolada gorzka z nadzieniem',
            'Czekolada karmelowa',
            'Czekolada Lindt',
            'Czekolada mleczna',
            'Czekolada mleczna z nadzieniem',
            'Czekolada Schogetten',
            'Czekolada z bakaliami',
            'Czekolada z herbatnikiem',
            'Czekolada z orzechami',
            'Czekoladki',
            'Delicje',
            'Deser',
            'Deser czekoladowy',
            'Deser karmelowy',
            'Deser lodowy',
            'Deser mleczny',
            'Deser śmietankowy',
            'Deser sojowy',
            'Donut',
            'Draże',
            'Draże czekoladowe',
            'Draże kokosowe',
            'Draże mleczne',
            'Drożdżówka z budyniem',
            'Drożdżówka z kruszonką',
            'Drożdżówka z marmoladą',
            'Drożdżówka z serem',
            'Dżem',
            'Dżem 100%',
            'Dżem agrestowy',
            'Dżem ananasowy',
            'Dżem brzoskwiniowy',
            'Dżem czereśniowy',
            'Dżem jagodowy',
            'Dżem jeżynowy',
            'Dżem malinowy',
            'Dżem morelowy',
            'Dżem pomarańczowy',
            'Dżem śliwkowy',
            'Dżem truskawkowy',
            'Dżem wiśniowy',
            'Dżem z czarnej porzeczki',
            'Dżem z kiwi',
            'Dżem z owoców leśnych',
            'Dżem żurawinowy',
            'Eklerki',
            'Erytrol',
            'Faworki',
            'Ferrero Rocher',
            'Galaretka',
            'Galaretka agrestowa',
            'Galaretka brzoskwiniowa',
            'Galaretka cytrynowa',
            'Galaretka malinowa',
            'Galaretka owocowa',
            'Galaretka pomarańczowa',
            'Galaretka truskawkowa',
            'Galaretka w kubeczku',
            'Gofry',
            'Groszek ptysiowy',
            'Guma do żucia',
            'Guma Mamba',
            'Guma orbit',
            'Gumy do żucia',
            'Herbatki',
            'Kakao surowe',
            'Kamyki',
            'Kanapka mleczna',
            'Kasztanki',
            'Kinder Czekolada',
            'Kisiel',
            'Kisiel brzoskwiniowy',
            'Kisiel o smaku żurawinowym',
            'Kisiel owoce leśne',
            'Kisiel owocowy kubek',
            'Kisiel pomarańczowy',
            'Kisiel Słodka Chwila',
            'Kisiel truskawkowy',
            'Konfitura',
            'Konfitura malinowa',
            'Konfitura poziomkowa',
            'Konfitura wiśniowa',
            'Konfitura z pomarańczy',
            'Konfitura z truskawek',
            'Krakersy',
            'Krakersy serowe',
            'Krakersy wielozbożowe',
            'Krem czekoladowy',
            'Krem kanapkowy',
            'Krem kokosowy',
            'Krem orzechowy',
            'Krem toffee',
            'Krówka cukierki',
            'Kruche ciastka',
            'Landrynki',
            'Lay\'s sticks',
            'Lizaki',
            'Lody',
            'Lody Algida',
            'Lody Algida Big Milk',
            'Lody bakaliowe',
            'Lody bez laktozy',
            'Lody biała czekolada',
            'Lody Big Milk',
            'Lody Carte d\'Or',
            'Lody czekoladowe',
            'Lody Guliwer',
            'Lody jagodowe',
            'Lody Jak dawniej',
            'Lody jogurtowe',
            'Lody Kaktus',
            'Lody Kanapka Lodowa',
            'Lody karmelowe',
            'Lody kawowe',
            'Lody kokosowe',
            'Lody koktajlowe',
            'Lody Magnum',
            'Lody Mövenpick',
            'Lody o smaku śmietankowym',
            'Lody Oreo',
            'Lody orzechowe',
            'Lody Oskar',
            'Lody owoce leśne',
            'Lody Rolada Lodowa',
            'Lody rożek',
            'Lody sandwich',
            'Lody śmietankowe',
            'Lody Sorbet',
            'Lody stracciatella',
            'Lody truskawkowe',
            'Lody waniliowe',
            'Lody wiśniowe',
            'M&M\'s',
            'M&M\'s czekoladowe',
            'M&M\'s z orzechami',
            'Makowiec',
            'Malaga',
            'Maltesers',
            'Marcepan',
            'Markizy',
            'Marmolada',
            'Masa Kajmak krówkowa',
            'Mentos',
            'Mentos fruit',
            'Mentos miętowy',
            'Michałki klasyczne',
            'Mieszanka bakaliowa',
            'Mieszanka studencka',
            'Migdały w czekoladzie',
            'Mleczna kanapka',
            'Monte',
            'Muffiny',
            'Nachos',
            'Orzechy w czekoladzie',
            'Pączki',
            'Paluszki',
            'Paluszki czekoladowe',
            'Paluszki o smaku ser cebulka',
            'Paluszki słone',
            'Paluszki z makiem',
            'Paluszki z sezamem',
            'Petitki Lubisie',
            'Piernik',
            'Pierniki',
            'Pierniki lukrowane',
            'Pierniki w czekoladzie',
            'Polewa',
            'Polewa czekoladowa',
            'Polewa krówkowa',
            'Popcorn',
            'Praliny',
            'Praliny Lindor',
            'Praliny nadziewane',
            'Prażynki',
            'Precelki',
            'Precle',
            'Ptasie mleczko',
            'Raffaello',
            'Rogalik',
            'Rożek francuski z jabłkiem',
            'Rurki',
            'Rurki waflowe',
            'Rurki włoskie',
            'Sasanki',
            'Sękacz',
            'Sernik',
            'Sezamki',
            'Skittles',
            'Śliwka nałęczowska w czekoladzie',
            'Śliwka w czekoladzie',
            'Słodzik',
            'Słodzik Erythol',
            'Słomka ptysiowa',
            'Śmiej żelki',
            'Sorbet',
            'Sorbet lodowy',
            'Stewia w proszku',
            'Strucla',
            'Strucla makowa',
            'Strucla orzechowa',
            'Strucla owocowa',
            'Strucla serowa',
            'Strucla wiśniowa',
            'Szarlotka',
            'Szybki budyń',
            'Tarta owocowa',
            'Tartaletka z owocami',
            'Tic Tac',
            'Tiki Taki',
            'Tiramisu',
            'Tort',
            'Wafelek Góralki',
            'Wafelek Grześki',
            'Wafelek Knopers',
            'Wafelek orzechowy',
            'Wafelek Prince Polo',
            'Wafelek Princessa',
            'Wafelek Teatralny',
            'Wafelek w czekoladzie',
            'Wafelki',
            'Wafelki Familijne',
            'Wafle Andruty suche',
            'Wafle do lodów',
            'Wata cukrowa',
            'Wiśnie w czekoladzie',
            'Żelatyna fix deserowa',
            'Żelki',
            'Żelki - Haribo',
            'Żelki Misie',
            'Żurawina w czekoladzie',

        ];
        $napoje = [
            '7 Up',
            'Advocat',
            'Ajerkoniak',
            'Aloe vera',
            'Baileys Irish Cream',
            'Bobo Frut',
            'Brandy',
            'Cabernet Sauvignon',
            'Caipirinha',
            'Campari',
            'Carlsberg',
            'Chardonnay',
            'Cherry Brandy',
            'Choco Drink - napój kakaowy',
            'Cin Cin',
            'Coca Cola',
            'Coca-Cola Cherry',
            'Coca-Cola Vanilla',
            'Curacao',
            'Cydr jabłkowy',
            'Cytrynówka',
            'Fanta',
            'Gin',
            'Herbata',
            'Herbata cytrynowa',
            'Herbata czarna',
            'Herbata czerwona',
            'Herbata czerwona Pu-Erh',
            'Herbata Earl Grey',
            'Herbata Lipton',
            'Herbata malinowa',
            'Herbata Melisa',
            'Herbata Mięta',
            'Herbata owocowa',
            'Herbata rumiankowa',
            'Herbata Saga',
            'Herbata z pokrzywy',
            'Herbata zielona',
            'Herbatka ziołowa',
            'Hortex',
            'Jagermeister',
            'Kawa',
            'Kawa 2w1',
            'Kawa 3w1',
            'Kawa Cappuccino',
            'Kawa Caramel',
            'Kawa Gold Rozpuszczalna',
            'Kawa Inka',
            'Kawa Macchiato',
            'Kawa Mocha',
            'Kawa Mokate',
            'Kawa mrożona',
            'Kawa Nescafe',
            'Kawa rozpuszczalna',
            'Kawa zbożowa',
            'Kawa zielona',
            'Koniak',
            'Kubuś',
            'Lipton Ice Tea',
            'Malibu',
            'Martini',
            'Martini',
            'Merlot',
            'Mirinda',
            'Mountain Dew',
            'Napój aloesowy',
            'Napój energetyczny',
            'Napój izotoniczny',
            'Napój kakaowy',
            'Napoje',
            'Nektar pomarańczowy',
            'Nestea Ice Tea',
            'Oranżada',
            'Oshee vitamin',
            'Pepsi Cola',
            'Pepsi Max',
            'Pepsi Twist',
            'Pina colada',
            'Pinot Blanc',
            'Pinot Noir',
            'Piwo',
            'Piwo bezalkoholowe',
            'Piwo ciemne pełne',
            'Piwo Corona',
            'Piwo Desperados',
            'Piwo Fosters Radler',
            'Piwo Guinness',
            'Piwo Harnaś',
            'Piwo imbirowe',
            'Piwo jasne pełne',
            'Piwo Karmi',
            'Piwo korzenne',
            'Piwo Książęce',
            'Piwo Lech',
            'Piwo Perła',
            'Piwo Pilsner Urquell',
            'Piwo pszeniczne',
            'Piwo Radler',
            'Piwo Redd\'s',
            'Piwo Tyskie',
            'Piwo Warka',
            'Piwo Żubr',
            'Piwo Żywiec',
            'Prosecco',
            'Red Bull',
            'Rum',
            'Sangria',
            'Sauvignon Blanc',
            'Schweppes',
            'Sheridan',
            'Sok',
            'Sok 100% pomarańcza z cząstkami',
            'Sok 100% pomarańcza z hiszpańską mandarynką',
            'Sok 100% pomarańcza z miąższem',
            'Sok 100% pomidor',
            'Sok 100% warzywny',
            'Sok ananasowy',
            'Sok aroniowy',
            'Sok bananowy',
            'Sok czarna porzeczka',
            'Sok czerwony grejpfrut',
            'Sok grejpfrutowy',
            'Sok imbirowy',
            'Sok jabłkowy',
            'Sok karotka',
            'Sok Kubuś',
            'Sok mandarynkowy',
            'Sok marchwiowy',
            'Sok multiwitamina',
            'Sok owocowo-warzywny',
            'Sok pomarańczowy',
            'Sok pomidorowy',
            'Sok Vega',
            'Sok Vitaminka',
            'Sok warzywny',
            'Sok wielowarzywny',
            'Sok winogronowy',
            'Sok z brzozy',
            'Sok z buraków',
            'Sok z cytryny',
            'Sok z czarnej porzeczki',
            'Sok z kiszonej kapusty',
            'Sok z kiszonych ogórków',
            'Sprite',
            'Syrop barmański',
            'Syrop cola',
            'Syrop do kawy',
            'Syrop kiwi',
            'Syrop klonowy',
            'Syrop malinowy',
            'Syrop pomarańczowy',
            'Syrop truskawkowy',
            'Syrop z agawy',
            'Syrop z kwiatów dzikiego bzu',
            'Syrop z pędów sosny',
            'Syrop z winogron',
            'Syrop żurawinowy',
            'Szampan',
            'Szampan półwytrawny',
            'Szampan słodki',
            'Szampan wytrawny',
            'Tequilla',
            'Tonik',
            'Tymbark',
            'Warka Radler',
            'Whisky',
            'Wino',
            'Wino białe półsłodkie',
            'Wino białe półwytrawne',
            'Wino białe wytrawne ',
            'Wino czerwone półsłodkie',
            'Wino czerwone słodkie',
            'Wino czerwone wytrawne',
            'Wino musujące',
            'Wino różowe',
            'Woda',
            'Woda gazowana',
            'Woda kokosowa',
            'Woda niegazowana',
            'Woda smakowa cytrynowa',
            'Woda smakowa malinowa',
            'Woda smakowa truskawkowa',
            'Woda sodowa',
            'Wódka',
            'Żubrówka',

        ];
        $dom = [
            'Aerozol do mebli',
            'Chusteczki czyszczące do łazienki',
            'Chusteczki do czyszczenia mebli',
            'Druciak',
            'Emulsja do mebli w płynie',
            'Folia aluminiowa',
            'Folia spożywcza',
            'Gąbki do zmywania',
            'Gąbkościerki ',
            'Jednorazowe rękawice',
            'Kostka WC',
            'Krochmal',
            'Kwasek cytrynowy',
            'Mleczko czyszczące',
            'Odkamieniacz',
            'Odplamiacz do białego',
            'Odplamiacz do koloru',
            'Odświeżacz powietrza',
            'Papier do pieczenia',
            'Pasta do butów',
            'Plaster taśma',
            'Plastry opatrunkowe',
            'Płyn antystatyczny',
            'Płyn czyszczący uniwersalny',
            'Płyn do czyszczenia',
            'Płyn do kabin prysznicowych',
            'Płyn do mycia naczyń',
            'Płyn do płukania',
            'Płyn do podług drewnianych',
            'Płyn do prania do białego',
            'Płyn do prania do koloru',
            'Płyn do prania hipoalergiczny',
            'Płyn do szyb',
            'Płyn do WC',
            'Płyn nabłyszczający do zmywarki',
            'Płyn usuwający pleśń i osady',
            'Proszek do czyszczenia',
            'Proszek do dywanów',
            'Proszek do prania do białego',
            'Proszek do prania do koloru',
            'Proszek do prania hipoalergiczny',
            'Ręcznik papierowy',
            'Ściereczki czyszczące do łazienki',
            'Ściereczki do czyszczenia mebli',
            'Ściereczki uniwersalne',
            'Ścierka z mikrofibry',
            'Sól ochronna do zmywarki',
            'Spirytus salicylowy',
            'Spray antybakteryjny',
            'Szampon do prania dywanów',
            'Szczotka do mycia naczyń',
            'Tabletki do zmywarki',
            'Woda demineralizowana',
            'Woda do prasowania',
            'Worki na śmieci',
            'Worki śniadaniowe',
            'Zawieszka do WC',
            'Zmywaki kuchenne',

        ];
        $higiena = [
            'Balsam do ciała',
            'Chusteczki do demakijażu',
            'Chusteczki do higieny intymnej',
            'Chusteczki higieniczne',
            'Chusteczki nawilżane',
            'Dezodorant damski spray',
            'Dezodorant damski w kulce',
            'Dezodorant damski w sztyfcie',
            'Dezodorant męski spray',
            'Dezodorant męski w kulce',
            'Dezodorant męski w sztyfcie',
            'Gąbki kąpielowe',
            'Golenie i depilacja',
            'Krem do depilacji',
            'Krem do rąk',
            'Krem do stóp',
            'Krem do twarzy',
            'Krem z filtrem',
            'Lakier do włosów',
            'Maseczka do twarzy',
            'Masło do ciała',
            'Maszynki do golenia',
            'Maszynki jednoczęściowe',
            'Maszynki z wkładami',
            'Mleczko do ciała',
            'Mleczko do demakijażu',
            'Mydła w kostce',
            'Mydło glicerynowe',
            'Mydło w płynie',
            'Myjki kąpielowe',
            'Nić dentystyczna',
            'Odżywka do włosów',
            'Oliwka do ciała',
            'Papier toaletowy',
            'Pasta do zębów',
            'Patyczki kosmetyczne',
            'Peeling do twarzy',
            'Perfumy',
            'Pianka do golenia',
            'Pianka do włosów',
            'Pieluchy',
            'Plastry do depilacji',
            'Płatki kosmetyczne',
            'Płyn do higieny intymnej',
            'Płyn do kąpieli',
            'Płyn do płukania ust',
            'Płyn micelarny',
            'Płyn po goleniu',
            'Płyny i chusteczki',
            'Podpaski',
            'Pomadka ochronna',
            'Prezerwatywy',
            'Sól do kąpieli',
            'Środek na insekty',
            'Środek na ukąszenia',
            'Szampon do włosów',
            'Szampon suchy',
            'Szczoteczka do zębów',
            'Tampony',
            'Tonik do twarzy',
            'Wata higieniczna',
            'Wazelina kosmetyczna',
            'Witaminy, suplementy',
            'Wkładki',
            'Wkładki laktacyjne',
            'Żel do golenia',
            'Żel do mycia twarzy',
            'Żel pod prysznic',
            'Zmywacz do paznokci',

        ];

        foreach ($warzywa as $item){
            Product::insert(['name' => $item, 'product_category_id' => 1]);
        }
        foreach ($ryby as $item){
            Product::insert(['name' => $item, 'product_category_id' => 2]);
        }
        foreach ($mieso as $item){
            Product::insert(['name' => $item, 'product_category_id' => 3]);
        }
        foreach ($nabial as $item){
            Product::insert(['name' => $item, 'product_category_id' => 4]);
        }
        foreach ($zboze as $item){
            Product::insert(['name' => $item, 'product_category_id' => 5]);
        }
        foreach ($przyprawy as $item){
            Product::insert(['name' => $item, 'product_category_id' => 6]);
        }
        foreach ($slodycze as $item){
            Product::insert(['name' => $item, 'product_category_id' => 7]);
        }
        foreach ($napoje as $item){
            Product::insert(['name' => $item, 'product_category_id' => 8]);
        }
        foreach ($higiena as $item){
            Product::insert(['name' => $item, 'product_category_id' => 9]);
        }
        foreach ($dom as $item){
            Product::insert(['name' => $item, 'product_category_id' => 10]);
        }

//        foreach ($names as $name){
//            Product::insert(['name' => $name]);
//        }

    }
}
